include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    cancel_subscriptions: true
    prefer_relative_imports: false
    avoid_relative_lib_imports: true
    avoid_unused_constructor_parameters: false
    library_private_types_in_public_api: false
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    prefer_final_fields: false