name: laamsui
description: "A design system with a collection Futter UI Widgets and dart extensions"
version: 0.0.2
homepage: https://laams.io

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  # Local Assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 
  # Local Fonts:
  fonts:
    - family: Ionicons
      fonts:
        - asset: assets/icons/Ionicons.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/icons/MaterialCommunityIcons.ttf
