name: laamsui
description: "A design system with a collection of Futter UI Widgets and dart extensions."
version: 0.6.6
homepage: https://laams.io
repository: https://github.com/najibkr/laamsui
issue_tracker: https://github.com/najibkr/laamsui/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  two_dimensional_scrollables: ^0.3.1
  flutter_keyboard_visibility: ^6.0.0
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Local Assets
  assets:
    - assets/svgs/

  # Local Fonts:
  fonts:
    - family: Ionicons
      fonts:
        - asset: assets/icons/Ionicons.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/icons/MaterialCommunityIcons.ttf
